# Generated by Django 3.2.8 on 2021-10-30 16:38

from django.db import migrations, models

import timary.models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email_id",
            field=models.CharField(
                default=timary.models.create_new_ref_number, max_length=10, unique=True
            ),
        ),
    ]
