# Generated by Django 3.2.8 on 2021-12-07 02:43

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="dailyhoursinput",
            managers=[
                ("all_hours", django.db.models.manager.Manager()),
            ],
        ),
    ]
