# Generated by Django 3.2.10 on 2022-03-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0002_alter_user_membership_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="membership_tier",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (5, "STARTER"),
                    (19, "PROFESSIONAL"),
                    (49, "BUSINESS"),
                    (1, "INVOICE_FEE"),
                ],
                default=5,
            ),
        ),
    ]
