# Generated by Django 3.2.8 on 2021-12-07 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0002_alter_dailyhoursinput_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="dailyhoursinput",
            managers=[],
        ),
    ]
