# Generated by Django 3.2.10 on 2022-03-20 01:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0004_auto_20220319_2015"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroOAuth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="xero_contact_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sentinvoice",
            name="xero_invoice_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="xero_tenant_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
