# Generated by Django 3.2.10 on 2021-12-26 19:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hours_start_date", models.DateField(blank=True, null=True)),
                ("hours_end_date", models.DateField(blank=True, null=True)),
                ("date_sent", models.DateField()),
                ("total_price", models.PositiveIntegerField()),
                (
                    "paid_status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "PENDING"), (2, "PAID")], default=1
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_snapshots",
                        to="timary.invoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
