# Generated by Django 3.2.8 on 2021-11-20 23:24

from django.db import migrations, models

import timary.models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0004_alter_dailyhoursinput_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyhoursinput",
            name="hours",
            field=models.DecimalField(
                decimal_places=1,
                default=1,
                max_digits=3,
                validators=[
                    timary.models.validate_less_than_24_hours,
                    timary.models.validate_greater_than_zero_hours,
                ],
            ),
        ),
    ]
