# Generated by Django 3.2.10 on 2022-01-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0005_sentinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="membership_tier",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "FREE"), (2, "BASIC"), (3, "PREMIUM")], default=1
            ),
        ),
    ]
