# Generated by Django 3.2.10 on 2022-03-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0005_auto_20220319_2015"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FreshbooksOAuth",
        ),
        migrations.DeleteModel(
            name="QuickbooksOAuth",
        ),
        migrations.DeleteModel(
            name="XeroOAuth",
        ),
        migrations.DeleteModel(
            name="ZohoOAuth",
        ),
        migrations.AddField(
            model_name="user",
            name="freshbooks_refresh_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="quickbooks_refresh_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="xero_refresh_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="zoho_refresh_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
