# Generated by Django 3.2.8 on 2021-12-05 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0005_alter_dailyhoursinput_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\+?1?\\d{8,15}$")
                ],
            ),
        ),
    ]
