# Generated by Django 3.2.10 on 2022-01-14 02:11

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0005_sentinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number_availability",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Mon", "Mon"),
                    ("Tue", "Tue"),
                    ("Wed", "Wed"),
                    ("Thu", "Thu"),
                    ("Fri", "Fri"),
                    ("Sat", "Sat"),
                    ("Sun", "Sun"),
                ],
                max_length=27,
                null=True,
            ),
        ),
    ]
