# Generated by Django 3.2.10 on 2022-03-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0006_auto_20220322_1910"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="sage_contact_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sentinvoice",
            name="sage_invoice_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sage_account_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sage_refresh_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
