# Generated by Django 3.2.15 on 2022-08-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0006_user_invoice_branding"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.IntegerField(
                choices=[(1, "INTERVAL"), (2, "MILESTONE")], default=1
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="milestone_step",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="milestone_total_steps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_interval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "DAILY"),
                    ("W", "WEEKLY"),
                    ("B", "BIWEEKLY"),
                    ("M", "MONTHLY"),
                    ("Q", "QUARTERLY"),
                    ("Y", "YEARLY"),
                ],
                default="M",
                max_length=1,
                null=True,
            ),
        ),
    ]
