# Generated by Django 3.2.8 on 2021-12-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0006_userprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
