# Generated by Django 3.2.15 on 2022-08-13 22:46
import random

from django.db import migrations, models

import timary.models


def assign_referrer_id_to_existing_users(apps, schema_editor):
    User = apps.get_model("timary", "User")
    for user in User.objects.all():
        user.referrer_id = str(random.randint(1000000000, 9999999999))
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0007_auto_20220812_1112"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referrer_id",
            field=models.CharField(
                default=timary.models.create_new_ref_number, max_length=10, null=True
            ),
        ),
        migrations.RunPython(
            assign_referrer_id_to_existing_users, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="user",
            name="referrer_id",
            field=models.CharField(
                default=timary.models.create_new_ref_number, max_length=10, unique=True
            ),
        ),
    ]
