# Generated by Django 3.2.15 on 2022-08-13 22:46

from django.db import migrations, models

import timary.models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0007_auto_20220812_1112"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referrer_id",
            field=models.CharField(
                default=timary.models.create_new_ref_number, max_length=10, unique=True
            ),
        ),
    ]
