# Generated by Django 3.2.10 on 2022-03-29 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0007_auto_20220328_1948"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentinvoice",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_snapshots",
                to="timary.invoice",
            ),
        ),
    ]
