# Generated by Django 3.2.10 on 2022-01-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0007_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_connect_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
