# Generated by Django 3.2.13 on 2022-04-16 16:25

from django.db import migrations, models
from django.db.migrations import RunPython

from timary.services.stripe_service import StripeService


def set_stripe_invoice_customer_ids(apps, schema_editor):
    User = apps.get_model("timary", "User")
    for user in User.objects.all():
        for invoice in user.get_invoices:
            StripeService.create_customer_for_invoice(invoice)


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0008_alter_sentinvoice_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email_recipient_stripe_customer_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(
            set_stripe_invoice_customer_ids, reverse_code=RunPython.noop
        ),
    ]
