# Generated by Django 3.2.10 on 2022-01-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0008_user_stripe_connect_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="membership_tier",
            field=models.PositiveSmallIntegerField(
                choices=[(5, "STARTER"), (19, "PROFESSIONAL"), (49, "BUSINESS")],
                default=5,
            ),
        ),
    ]
