# Generated by Django 3.2.15 on 2022-08-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0008_user_referrer_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="freshbooks_client_id",
            new_name="accounting_customer_id",
        ),
        migrations.RenameField(
            model_name="sentinvoice",
            old_name="freshbooks_invoice_id",
            new_name="accounting_invoice_id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="freshbooks_account_id",
            new_name="accounting_org",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="freshbooks_refresh_token",
            new_name="accounting_org_id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="quickbooks_realm_id",
            new_name="accounting_refresh_token",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="quickbooks_customer_ref_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="sage_contact_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="xero_contact_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="zoho_contact_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="zoho_contact_persons_id",
        ),
        migrations.RemoveField(
            model_name="sentinvoice",
            name="quickbooks_invoice_id",
        ),
        migrations.RemoveField(
            model_name="sentinvoice",
            name="sage_invoice_id",
        ),
        migrations.RemoveField(
            model_name="sentinvoice",
            name="xero_invoice_id",
        ),
        migrations.RemoveField(
            model_name="sentinvoice",
            name="zoho_invoice_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="quickbooks_refresh_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="sage_account_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="sage_refresh_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="xero_refresh_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="xero_tenant_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="zoho_organization_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="zoho_refresh_token",
        ),
    ]
