# Generated by Django 3.2.10 on 2022-01-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0009_alter_user_membership_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
