# Generated by Django 3.2.13 on 2022-04-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0009_invoice_email_recipient_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentinvoice",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sentinvoice",
            name="paid_status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "PENDING"), (2, "PAID"), (3, "FAILED")], default=1
            ),
        ),
    ]
