# Generated by Django 4.0.7 on 2022-10-04 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0010_rename_hourly_rate_invoice_invoice_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="membership_tier",
        ),
    ]
