# Generated by Django 3.2.10 on 2022-01-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0010_user_stripe_subscription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_payouts_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
