# Generated by Django 4.0.8 on 2022-10-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0011_remove_user_membership_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timer_is_active",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
