# Generated by Django 3.2.10 on 2022-01-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0006_user_phone_number_availability"),
        ("timary", "0011_user_stripe_payouts_enabled"),
    ]

    operations = []
