# Generated by Django 4.1.2 on 2022-10-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0012_user_timer_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_connect_reason",
            field=models.IntegerField(
                choices=[(1, "NONE"), (2, "PENDING"), (3, "MORE_INFO")], default=3
            ),
        ),
    ]
