# Generated by Django 3.2.13 on 2022-07-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0013_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
