# Generated by Django 4.1.2 on 2022-11-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0013_user_stripe_connect_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentinvoice",
            name="paid_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "NOT_STARTED"),
                    (1, "PENDING"),
                    (2, "PAID"),
                    (3, "FAILED"),
                ],
                default=0,
            ),
        ),
    ]
