# Generated by Django 3.2.10 on 2022-02-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0014_user_quickbooks_realm_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="quickbooks_customer_ref_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sentinvoice",
            name="quickbooks_invoice_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
