# Generated by Django 3.2.13 on 2022-07-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0014_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invoice_branding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
