# Generated by Django 3.2.10 on 2022-02-06 19:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0015_auto_20220206_1206"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickbooksOAuth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
