# Generated by Django 4.1.2 on 2022-12-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0015_alter_sentinvoice_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_status",
            field=models.IntegerField(
                choices=[(1, "TRIAL"), (2, "ACTIVE"), (3, "INACTIVE")], default=1
            ),
        ),
    ]
