# Generated by Django 3.2.10 on 2022-02-13 18:51

from django.db import migrations, models

import timary.models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0017_auto_20220212_1820"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyhoursinput",
            name="hours",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=4,
                validators=[
                    timary.models.validate_less_than_24_hours,
                    timary.models.validate_greater_than_zero_hours,
                ],
            ),
        ),
    ]
