# Generated by Django 3.2.10 on 2022-03-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0018_alter_dailyhoursinput_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_archived",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
