# Generated by Django 4.1.4 on 2022-12-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0018_invoice_is_paused"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyhoursinput",
            name="recurring_logic",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
