# Generated by Django 3.2.10 on 2022-03-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0019_invoice_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total_budget",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
