# Generated by Django 4.1.4 on 2022-12-31 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0020_alter_invoice_invoice_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
