# Generated by Django 4.1.4 on 2022-12-31 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0021_alter_invoice_invoice_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="referrer_id",
            new_name="referral_id",
        ),
    ]
