# Generated by Django 4.1.4 on 2022-12-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0022_rename_referrer_id_user_referral_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referrer_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
