# Generated by Django 4.1.4 on 2022-12-31 23:16

from django.db import migrations, models


def update_stripe_subscription_price(apps, schema_editor):
    User = apps.get_model("timary", "User")
    User.objects.all().update(stripe_subscription_recurring_price=29)


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0023_user_referrer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_recurring_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            update_stripe_subscription_price, reverse_code=migrations.RunPython.noop
        ),
    ]
