# Generated by Django 4.1.4 on 2023-01-10 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0024_user_stripe_subscription_recurring_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="email_recipient",
            new_name="client_email",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="email_recipient_name",
            new_name="client_name",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="email_recipient_stripe_customer_id",
            new_name="client_stripe_customer_id",
        ),
    ]
