# Generated by Django 4.1.4 on 2023-01-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0025_rename_email_recipient_invoice_client_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentinvoice",
            name="hours_end_date",
        ),
        migrations.RemoveField(
            model_name="sentinvoice",
            name="hours_start_date",
        ),
    ]
