# Generated by Django 4.1.4 on 2023-01-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0026_singleinvoice_singleinvoicelineitem_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="singleinvoice",
            name="timary_singleinvoice_either_interval_or_installments",
        ),
    ]
