# Generated by Django 4.1.4 on 2023-01-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0026_remove_sentinvoice_hours_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_interval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("W", "WEEKLY"),
                    ("B", "BIWEEKLY"),
                    ("M", "MONTHLY"),
                    ("Q", "QUARTERLY"),
                    ("Y", "YEARLY"),
                ],
                default="M",
                max_length=1,
                null=True,
            ),
        ),
    ]
