# Generated by Django 4.1.4 on 2023-01-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0027_alter_invoice_invoice_interval"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DailyHoursInput",
            new_name="HoursLineItem",
        ),
    ]
