# Generated by Django 4.1.4 on 2023-01-12 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0028_rename_dailyhoursinput_hourslineitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hourslineitem",
            name="hours",
        ),
        migrations.RemoveField(
            model_name="hourslineitem",
            name="notes",
        ),
        migrations.AddField(
            model_name="hourslineitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
        ),
        migrations.AddField(
            model_name="hourslineitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name="hourslineitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="timary.invoice",
            ),
        ),
    ]
