# Generated by Django 4.1.4 on 2023-01-12 16:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("timary", "0030_hourslineitem_between_0_and_24_hours"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_interval",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_rate",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_type",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="last_date",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="milestone_step",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="milestone_total_steps",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="next_date",
        ),
        migrations.AddField(
            model_name="invoice",
            name="balance_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=100,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=100,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.CreateModel(
            name="RecurringInvoice",
            fields=[
                (
                    "invoice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="timary.invoice",
                    ),
                ),
                ("next_date", models.DateField(blank=True, null=True)),
                ("last_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("timary.invoice",),
        ),
        migrations.CreateModel(
            name="IntervalInvoice",
            fields=[
                (
                    "recurringinvoice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="timary.recurringinvoice",
                    ),
                ),
                (
                    "invoice_interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("W", "WEEKLY"),
                            ("B", "BIWEEKLY"),
                            ("M", "MONTHLY"),
                            ("Q", "QUARTERLY"),
                            ("Y", "YEARLY"),
                        ],
                        default="M",
                        max_length=1,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("timary.recurringinvoice",),
        ),
        migrations.CreateModel(
            name="MilestoneInvoice",
            fields=[
                (
                    "recurringinvoice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="timary.recurringinvoice",
                    ),
                ),
                ("milestone_total_steps", models.IntegerField(blank=True, null=True)),
                (
                    "milestone_step",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("timary.recurringinvoice",),
        ),
        migrations.CreateModel(
            name="WeeklyInvoice",
            fields=[
                (
                    "recurringinvoice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="timary.recurringinvoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("timary.recurringinvoice",),
        ),
    ]
