# Generated by Django 4.1.4 on 2023-01-12 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0031_alter_invoice_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleInvoice",
            fields=[
                (
                    "invoice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="timary.invoice",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(0, "DRAFT"), (1, "SENT"), (2, "ARCHIVE")],
                        default=0,
                        null=True,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "send_reminder",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "late_penalty",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "late_penalty_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=5, null=True
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=5, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=4, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("timary.invoice",),
        ),
    ]
