# Generated by Django 4.1.4 on 2023-01-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0032_singleinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="hourslineitem",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
