# Generated by Django 4.1.4 on 2023-01-12 22:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("timary", "0033_hourslineitem_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_tracked", models.DateField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=9),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=1, max_digits=9),
                ),
                (
                    "sent_invoice_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="hourslineitem",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="hourslineitem",
            name="between_0_and_24_hours",
        ),
        migrations.RemoveField(
            model_name="hourslineitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="hourslineitem",
            name="date_tracked",
        ),
        migrations.RemoveField(
            model_name="hourslineitem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="hourslineitem",
            name="id",
        ),
        migrations.RemoveField(
            model_name="hourslineitem",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="hourslineitem",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="hourslineitem",
            name="sent_invoice_id",
        ),
        migrations.RemoveField(
            model_name="hourslineitem",
            name="unit_price",
        ),
        migrations.RemoveField(
            model_name="hourslineitem",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="lineitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="timary.invoice",
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="hourslineitem",
            name="lineitem_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="timary.lineitem",
            ),
            preserve_default=False,
        ),
    ]
