# Generated by Django 4.1.4 on 2023-01-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0034_lineitem_alter_hourslineitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="date_tracked",
            field=models.DateField(blank=True, null=True),
        ),
    ]
