# Generated by Django 4.1.4 on 2023-01-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0035_alter_lineitem_date_tracked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
