# Generated by Django 4.1.4 on 2023-01-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0036_alter_lineitem_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleinvoice",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(0, "DRAFT"), (1, "SENT")], default=0, null=True
            ),
        ),
    ]
