# Generated by Django 4.1.4 on 2023-01-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0037_alter_singleinvoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentinvoice",
            name="paid_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "NOT STARTED"),
                    (1, "PENDING"),
                    (2, "PAID"),
                    (3, "FAILED"),
                ],
                default=0,
            ),
        ),
    ]
