# Generated by Django 4.1.4 on 2023-01-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0038_alter_sentinvoice_paid_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="balance_due",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=100, max_digits=6, null=True
            ),
        ),
    ]
