# Generated by Django 4.1.4 on 2023-01-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0039_alter_invoice_balance_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleinvoice",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(0, "DRAFT"), (1, "FINAL")], default=0, null=True
            ),
        ),
    ]
