# Generated by Django 4.1.4 on 2023-01-29 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timary", "0043_user_timezone_alter_lineitem_date_tracked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentinvoice",
            name="hourly_rate_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=100,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
