# Generated by Django 4.1.6 on 2023-02-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timary", "0044_sentinvoice_hourly_rate_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentinvoice",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="singleinvoice",
            name="installments",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "ONE"),
                    (2, "TWO"),
                    (3, "THREE"),
                    (4, "FOUR"),
                    (5, "FIVE"),
                    (6, "SIX"),
                    (7, "SEVEN"),
                    (8, "EIGHT"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="singleinvoice",
            name="next_installment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
