# Generated by Django 4.1.6 on 2023-03-06 15:33

from django.db import migrations, models

import timary.models


class Migration(migrations.Migration):
    dependencies = [
        ("timary", "0047_recurringinvoice_sms_ping_today"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_tasks",
            field=models.JSONField(
                blank=True, default=timary.models.default_tasks, null=True
            ),
        ),
    ]
