# Generated by Django 4.1.6 on 2023-03-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timary", "0050_sentinvoice_email_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentinvoice",
            name="date_paid",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
