# Generated by Django 4.1.6 on 2023-03-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timary", "0051_sentinvoice_date_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
