# Generated by Django 4.1.8 on 2023-04-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timary", "0054_proposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyinvoice",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
