# Generated by Django 4.1.8 on 2023-05-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timary", "0055_weeklyinvoice_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="timer_is_active",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
