# Generated by Django 4.1.8 on 2023-05-19 04:56

from django.db import migrations, models

import timary.models


class Migration(migrations.Migration):
    dependencies = [
        ("timary", "0055_weeklyinvoice_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="timer_is_active",
            field=models.JSONField(
                blank=True, default=timary.models.default_timer, null=True
            ),
        ),
    ]
