name: Django CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install
    - name: Install operating system dependencies
      run: python -m playwright install-deps
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: make test
    - name: Run ui tests
      run: make test-ui
